package com.naman14.timberx.util

object Constants {

    const val SONGS_LIST = "songs_list"
    const val QUEUE_TITLE = "queue_title"
    const val SEEK_TO_POS = "seek_to_pos"
    const val ACTION_SET_MEDIA_STATE = "action_set_media_state"
    const val ACTION_REPEAT_SONG = "action_repeat_song"
    const val ACTION_REPEAT_QUEUE = "action_repeat_queue"
    const val ACTION_PLAY_NEXT = "action_play_next"
    const val ACTION_QUEUE_REORDER = "action_queue_reorder"
    const val ACTION_SONG_DELETED = "action_song_deleted"
    const val ACTION_ADDED_TO_PLAYLIST = "action_added_to_playlist"
    const val ACTION_REMOVED_FROM_PLAYLIST = "action_removed_from_playlist"
    const val ACTION_RESTORE_MEDIA_SESSION = "action_restore_media_session"
    const val ACTION_CAST_CONNECTED = "action_cast_connected"
    const val ACTION_CAST_DISCONNECTED= "action_cast_disconnected"
    const val ALBUM = "album"
    const val ARTIST = "artist"
    const val SONG = "song"
    const val PLAYLIST = "playlist"
    const val GENRE = "genre"
    const val QUEUE = "queue"
    const val QUEUE_FROM = "queue_from"
    const val QUEUE_TO = "queue_to"
    const val REPEAT_MODE = "repeat_mode"
    const val SHUFFLE_MODE = "shuffle_mode"
    const val CATEGORY_SONG_DATA = "category_song_data"
    const val NOW_PLAYING = "now_playing"
    const val ACTION = "action"
    const val ACTION_PLAY_PAUSE = "action_play_pause"
    const val ACTION_NEXT = "action_next"
    const val ACTION_PREVIOUS = "action_previous"
    const val SONG_SORT_ORDER = "song_sort_order"
    const val CAST_SERVER_PORT = 5050
    const val CAST_MUSIC_METADATA_ID = "metadata_id"
    const val CAST_MUSIC_METADATA_ALBUM_ID = "metadata_album_id"
    const val APP_PACKAGE_NAME = "com.naman14.timberx"

}